leftnav:
- identifier: 3ac6f70c-8f1e-4b5f-aaf8-5c6682c8eda3
  name: Online Publication
  pageRef: /external-resources/online-publication_3ac6f70c-8f1e-4b5f-aaf8-5c6682c8eda3
  weight: 10
- identifier: 512541a4-40a1-46cf-83b2-5fa6c2422481
  name: Test Page
  pageRef: /pages/test-page
  weight: 20
- identifier: 3e3520c8-243a-4164-89bf-c2504f1f18d8
  name: c4103
  pageRef: /external-resources/c4103
  weight: 30
