leftnav:
- identifier: external--539947917-1695230431281
  name: Online Publication
  url: https://people.csail.mit.edu/jshun/6506-s23/
  weight: 10
- identifier: 512541a4-40a1-46cf-83b2-5fa6c2422481
  name: Test Page
  pageRef: /pages/test-page
  weight: 20
- identifier: 3e3520c8-243a-4164-89bf-c2504f1f18d8
  name: c4103
  pageRef: /external-resources/c4103
  weight: 30
